# Site settings
title: Task Force Omega
email: contact@taskforceomega.co.uk
url: https://taskforceomega.co.uk/index.html
description: "Task Force Omega is a global provider of military training, security management and logistical support."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#C6C49D'

# Images
images:
  icon: 'https://cdn.discordapp.com/attachments/538859036385345547/588033812139737098/tfo-omega-white.png'
  header: 'https://cdn.discordapp.com/attachments/472357540273979422/659553494876946436/ed77be88-50ee-42b5-9773-01aad6cd8a20_Thumbnail_1.PNG'
  security: 'https://cdn.discordapp.com/attachments/472357540273979422/663099848169488404/Forest.PNG'
  join-us: 'https://cdn.discordapp.com/attachments/472357540273979422/659167205321211919/82c63bf0-6fca-4bbe-afd0-a57a2af8889b_Thumbnail.PNG'
  contact-us: 'https://cdn.discordapp.com/attachments/472357540273979422/663099673250365450/CJU.PNG'
  #objective: 'https://cdn.discordapp.com/attachments/464940351153766400/651009780051083264/2019-12-02-10-39-02.jpg'
  
# Footer settings
footer: Blackstone

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
#social:
# - title: twitter
#   url: https://twitter.com/SBootstrap
# - title: facebook
#   url:
# - title: stack-overflow
#   url: http://stackoverflow.com/questions/tagged/jekyll
# - title: bitbucket
#   url: http://bitbucket.org/jekyll
# - title: github
#   url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
