# Site settings
title: Task Force Omega
email: contact@taskforceomega.co.uk
url: https://taskforceomega.co.uk/index.html
description: "Task Force Omega is a global provider of military training, security operations and logistical support."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
#  secondary-dark: '#'
  links: '#C6C49D'

# Images
images:
  header: 'https://cdn.discordapp.com/attachments/472357540273979422/570231668602961920/image4.jpg'
  forward-operations:
  security: 'https://cdn.discordapp.com/attachments/472357540273979422/570231669873967115/image3.jpg'
  logistics:
  join-us: 'https://cdn.discordapp.com/attachments/472357540273979422/578590244983799821/TFOEcho_TomClancysGhostReconWildlandsStandardEdition_20190511_23-58-34.png'
  #about-us
  contact-us: 'https://cdn.discordapp.com/attachments/472357540273979422/544772653274103829/image0.jpg'
# Footer settings
footer: Task Force Omega

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
#social:
# - title: twitter
#   url: https://twitter.com/SBootstrap
# - title: facebook
#   url:
# - title: stack-overflow
#   url: http://stackoverflow.com/questions/tagged/jekyll
# - title: bitbucket
#   url: http://bitbucket.org/jekyll
# - title: github
#   url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
