# Site settings
title: Task Force Omega
email: contact@taskforceomega.co.uk
url: https://taskforceomega.co.uk/index.html
description: "Task Force Omega is an Xbox One Milsim Community"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#C6C49D'
  
# Images
images:
  header-image: 'https://cdn.discordapp.com/attachments/472357540273979422/570231668602961920/image4.jpg'

# Footer settings
footer: Task Force Omega

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
#social:
# - title: twitter
#   url: https://twitter.com/SBootstrap
# - title: facebook
#   url:
# - title: stack-overflow
#   url: http://stackoverflow.com/questions/tagged/jekyll
# - title: bitbucket
#   url: http://bitbucket.org/jekyll
# - title: github
#   url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
