# Site settings
title: Task Force Omega
email: contact@taskforceomega.co.uk
url: https://taskforceomega.co.uk/index.html
description: "Task Force Omega is a global provider of military training, security management and logistical support."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#C6C49D'

# Images
images:
  icon: 'https://cdn.discordapp.com/attachments/464940351153766400/672596141325680649/server-icon-invert.png'
  header: 'https://media.discordapp.net/attachments/943135202874634280/1078527218113847446/Arma_Reforger_Game_Preview_40.png'
  security: 'https://cdn.discordapp.com/attachments/538859036385345547/1085003286983229550/Arma_Reforger_Game_Preview_60.png'
  join-us: 'https://cdn.discordapp.com/attachments/1065039562310697070/1072540849990283264/4a53b14e-81d0-4b26-99b0-2e3776872833.png'
  contact-us: 'https://cdn.discordapp.com/attachments/943135202874634280/1085402691754266664/7ee7dc9c-bf57-4385-a61b-47f63a3231c4.png'

  #objective: 'https://cdn.discordapp.com/attachments/464940351153766400/651009780051083264/2019-12-02-10-39-02.jpg'
  
# Footer settings
footer: Blackstone

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
#social:
# - title: twitter
#   url: https://twitter.com/SBootstrap
# - title: facebook
#   url:
# - title: stack-overflow
#   url: http://stackoverflow.com/questions/tagged/jekyll
# - title: bitbucket
#   url: http://bitbucket.org/jekyll
# - title: github
#   url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
